// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnsddGBcU-_ncIPcht3KfHPuvgl8cPEo',
    appId: '1:652374646493:web:b0e18a1b379587f4c9c534',
    messagingSenderId: '652374646493',
    projectId: 'reskindev-769d3',
    authDomain: 'reskindev-769d3.firebaseapp.com',
    storageBucket: 'reskindev-769d3.firebasestorage.app',
    measurementId: 'G-MQN9XM0SZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnsddGBcU-_ncIPcht3KfHPuvgl8cPEo',
    appId: '1:652374646493:android:32470425381f17d4c9c534',
    messagingSenderId: '652374646493',
    projectId: 'reskindev-769d3',
    storageBucket: 'reskindev-769d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8sO11OHfOYjB8-RIrPDep1ENKHTjVgw',
    appId: '1:652374646493:ios:672c1167ee1ef92ec9c534',
    messagingSenderId: '652374646493',
    projectId: 'reskindev-769d3',
    storageBucket: 'reskindev-769d3.firebasestorage.app',
    iosBundleId: 'com.reskindevdotcom.reskindev',
  );
}
